const fs = require('fs-extra');
const path = require('path');
const logger = require('./logger');
const { capitalize } = require('./utils');

const placeholderPlist = (flavorName) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- Replace this placeholder with the real GoogleService-Info.plist for the "${flavorName}" flavor (download it from the Firebase console). -->
</dict>
</plist>
`;

const xcconfig = ({ flavorName, packageName, appName }) => `// Auto-generated by rn-multi-env for the "${flavorName}" flavor.
// Reference this file from a matching Xcode build configuration (see below).

// react-native-config reads variables from this env file at build time.
ENVFILE = .env.${flavorName}

${packageName ? `PRODUCT_BUNDLE_IDENTIFIER = ${packageName}` : `// PRODUCT_BUNDLE_IDENTIFIER = com.yourcompany.${flavorName}`}
DISPLAY_NAME = ${appName || flavorName}
`;

function printIosSetupSteps({ flavorName, configName }) {
  logger.bold('\n📋 Manual Xcode steps to finish iOS support for this flavor:');
  logger.dim('  1. Open ios/<App>.xcodeproj (or .xcworkspace) in Xcode.');
  logger.dim('  2. Project ▸ Info ▸ Configurations: duplicate Debug and Release as');
  logger.dim(`     "Debug.${flavorName}" and "Release.${flavorName}".`);
  logger.dim("  3. Set each new configuration's \"Based on configuration file\" to");
  logger.dim(`     config/${configName}.xcconfig.`);
  logger.dim(`  4. Product ▸ Scheme ▸ Manage Schemes: add a "${flavorName}" scheme`);
  logger.dim('     and point its Run/Archive build configs at the new ones.');
  logger.dim(`  5. Drag GoogleService-Info-${flavorName}.plist into the project (replace`);
  logger.dim('     the placeholder with the real Firebase file) and copy it during build.');
  logger.dim(`  Run with: npx react-native run-ios --scheme ${flavorName}\n`);
}

async function createIosFiles({ paths, flavorName, packageName, appName }) {
  if (!(await fs.pathExists(paths.ios))) {
    logger.warn('⚠️  iOS folder not found. Skipping iOS flavor support.');
    return;
  }

  const configName = capitalize(flavorName);
  const plistPath = path.join(paths.ios, `GoogleService-Info-${flavorName}.plist`);
  const xcconfigPath = path.join(paths.iosConfig, `${configName}.xcconfig`);

  if (!(await fs.pathExists(plistPath))) {
    await fs.writeFile(plistPath, placeholderPlist(flavorName));
    logger.step(`📱 Created placeholder iOS plist for '${flavorName}'`);
  }

  await fs.ensureDir(paths.iosConfig);
  if (!(await fs.pathExists(xcconfigPath))) {
    await fs.writeFile(xcconfigPath, xcconfig({ flavorName, packageName, appName }));
    logger.step(`📱 Created ios/config/${configName}.xcconfig`);
  }

  printIosSetupSteps({ flavorName, configName });
}

async function removeIosFiles({ paths, flavorName, dryRun }) {
  const targets = [
    path.join(paths.ios, `GoogleService-Info-${flavorName}.plist`),
    path.join(paths.iosConfig, `${capitalize(flavorName)}.xcconfig`),
  ];

  for (const target of targets) {
    if (await fs.pathExists(target)) {
      if (dryRun) {
        logger.note(`[DRY RUN] Would remove ${path.basename(target)}`);
      } else {
        await fs.remove(target);
        logger.warn(`🧹 Removed ${path.basename(target)}`);
      }
    }
  }
}

module.exports = { createIosFiles, removeIosFiles, printIosSetupSteps, placeholderPlist, xcconfig };
